/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourceallocationsoftware.ViewClasses;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import resourceallocationsoftware.ControllerClasses.DatabaseHandler;
import resourceallocationsoftware.ControllerClasses.HallManager;
import resourceallocationsoftware.ModelClasses.Admin;
import resourceallocationsoftware.ModelClasses.Hall;
import java.util.List;
import java.util.ArrayList;
import java.util.Vector;
/**
 *
 * @author shanu
 */
public class AdminUI extends javax.swing.JFrame {

    private Admin admin;
    
    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
        setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        initMoving(AdminUI.this);
        fetchHallData();
        fetchBookingData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new RoundPanel(50, 50, 50, 50);
        jPanel3 = new RoundPanel(50, 50, 0, 0);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nicLabel = new RoundLabel(20, 20, 20, 20);
        jPanel2 = new RoundPanel(30, 30, 30, 30);
        jPanel4 = new RoundPanel(30, 30, 30, 30);
        jLabel1 = new RoundLabel(30, 30, 30, 30);
        jPanel8 = new RoundPanel(30, 30, 30, 30);
        jPanel9 = new RoundPanel(20, 20, 20, 20);
        jLabel6 = new javax.swing.JLabel();
        hallNoTf = new javax.swing.JTextField();
        jPanel10 = new RoundPanel(30, 30, 30, 30);
        jPanel11 = new RoundPanel(20, 20, 20, 20);
        jLabel7 = new javax.swing.JLabel();
        capacityTf = new javax.swing.JTextField();
        jPanel12 = new RoundPanel(30, 30, 30, 30);
        jPanel13 = new RoundPanel(20, 20, 20, 20);
        jLabel8 = new javax.swing.JLabel();
        pricingTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel5 = new RoundPanel(30, 30, 30, 30);
        jLabel9 = new RoundLabel(30, 30, 30, 30);
        jScrollPane2 = new javax.swing.JScrollPane();
        hallData = new resourceallocationsoftware.ViewClasses.Table.Table();
        jPanel6 = new RoundPanel(30, 30, 30, 30);
        jLabel10 = new RoundLabel(30, 30, 30, 30);
        jPanel15 = new RoundPanel(20, 20, 20, 20);
        jPanel17 = new RoundPanel(10, 10, 10, 10);
        jLabel13 = new RoundLabel(10, 10, 10, 10);
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel20 = new RoundPanel(20, 20, 20, 20);
        jPanel21 = new RoundPanel(10, 10, 10, 10);
        jLabel14 = new RoundLabel(10, 10, 10, 10);
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel7 = new RoundPanel(30, 30, 30, 30);
        jLabel11 = new RoundLabel(30, 30, 30, 30);
        jLabel17 = new javax.swing.JLabel();
        dateRdBtn = new javax.swing.JRadioButton();
        customerNicRdBtn = new javax.swing.JRadioButton();
        bookingSearchBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        customerNicTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTable = new resourceallocationsoftware.ViewClasses.Table.Table();
        jPanel1 = new RoundPanel(30, 30, 30, 30);
        jLabel5 = new RoundLabel(30, 30, 30, 30);
        customerSearchBtn = new javax.swing.JButton();
        jPanel16 = new RoundPanel(30, 30, 30, 30);
        jPanel14 = new RoundPanel(20, 20, 20, 20);
        jLabel12 = new javax.swing.JLabel();
        customerNicTf = new javax.swing.JTextField();
        closeBtn = new RoundLabel(0, 0, 50, 0);
        goBackBtn = new RoundLabel(0, 0, 50, 0);
        minimizeBtn = new RoundLabel(0, 0, 50, 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelMoving.setBackground(new java.awt.Color(57, 72, 103));
        panelMoving.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel3.setBackground(new java.awt.Color(57, 72, 103));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 800));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_admin_settings_male_75px.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 251, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMIN");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 251, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("menu");
        jLabel4.setToolTipText("");

        nicLabel.setBackground(new java.awt.Color(57, 72, 103));
        nicLabel.setFont(new java.awt.Font("Poppins", 1, 8)); // NOI18N
        nicLabel.setForeground(new java.awt.Color(247, 251, 255));
        nicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nicLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(228, 232, 235));
        jPanel2.setPreferredSize(new java.awt.Dimension(1075, 750));

        jPanel4.setBackground(new java.awt.Color(247, 251, 255));

        jLabel1.setBackground(new java.awt.Color(247, 251, 255));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 72, 103));
        jLabel1.setText("Hall Manager");

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel9.setBackground(new java.awt.Color(247, 251, 255));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(217, 50));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(155, 164, 181));
        jLabel6.setText("Hall no");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 18));

        hallNoTf.setBackground(new java.awt.Color(247, 251, 255));
        hallNoTf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        hallNoTf.setForeground(new java.awt.Color(67, 67, 67));
        hallNoTf.setToolTipText("");
        hallNoTf.setActionCommand("<Not Set>");
        hallNoTf.setBorder(null);
        hallNoTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hallNoTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hallNoTfFocusLost(evt);
            }
        });
        hallNoTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hallNoTfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hallNoTfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hallNoTfMouseExited(evt);
            }
        });
        hallNoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallNoTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hallNoTf, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(hallNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel11.setBackground(new java.awt.Color(247, 251, 255));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(217, 50));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(155, 164, 181));
        jLabel7.setText("Capacity");
        jLabel7.setPreferredSize(new java.awt.Dimension(70, 18));

        capacityTf.setBackground(new java.awt.Color(247, 251, 255));
        capacityTf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        capacityTf.setForeground(new java.awt.Color(67, 67, 67));
        capacityTf.setToolTipText("");
        capacityTf.setActionCommand("<Not Set>");
        capacityTf.setBorder(null);
        capacityTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                capacityTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                capacityTfFocusLost(evt);
            }
        });
        capacityTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capacityTfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                capacityTfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                capacityTfMouseExited(evt);
            }
        });
        capacityTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(capacityTf, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(capacityTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel13.setBackground(new java.awt.Color(247, 251, 255));
        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(217, 50));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(155, 164, 181));
        jLabel8.setText("Pricing");
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 18));

        pricingTf.setBackground(new java.awt.Color(247, 251, 255));
        pricingTf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pricingTf.setForeground(new java.awt.Color(67, 67, 67));
        pricingTf.setToolTipText("");
        pricingTf.setActionCommand("<Not Set>");
        pricingTf.setBorder(null);
        pricingTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pricingTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pricingTfFocusLost(evt);
            }
        });
        pricingTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pricingTfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pricingTfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pricingTfMouseExited(evt);
            }
        });
        pricingTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricingTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricingTf, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pricingTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel13);

        addBtn.setBackground(new java.awt.Color(57, 72, 103));
        addBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(155, 164, 181));
        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(57, 72, 103));
        updateBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(155, 164, 181));
        updateBtn.setText("Update");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(57, 72, 103));
        deleteBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(155, 164, 181));
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(247, 251, 255));

        jLabel9.setBackground(new java.awt.Color(247, 251, 255));
        jLabel9.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(57, 72, 103));
        jLabel9.setText("Hall Data");

        hallData.setForeground(new java.awt.Color(155, 164, 181));
        hallData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall no", "Capacity", "Pricing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hallData.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        hallData.setSelectionBackground(new java.awt.Color(57, 72, 103));
        hallData.setSelectionForeground(new java.awt.Color(255, 255, 255));
        hallData.getTableHeader().setReorderingAllowed(false);
        hallData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hallDataFocusLost(evt);
            }
        });
        hallData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hallDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(hallData);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane2.setVerticalScrollBar(new resourceallocationsoftware.ViewClasses.Table.ScrollBar());

        jPanel6.setBackground(new java.awt.Color(247, 251, 255));

        jLabel10.setBackground(new java.awt.Color(247, 251, 255));
        jLabel10.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(57, 72, 103));
        jLabel10.setText("Statistics");

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setPreferredSize(new java.awt.Dimension(165, 178));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 5));

        jPanel17.setBackground(new java.awt.Color(247, 251, 255));
        jPanel17.setPreferredSize(new java.awt.Dimension(157, 170));

        jLabel13.setBackground(new java.awt.Color(228, 232, 235));
        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(57, 72, 103));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total Income");

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(155, 164, 181));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("345000");

        jSeparator2.setBackground(new java.awt.Color(57, 72, 103));
        jSeparator2.setForeground(new java.awt.Color(57, 72, 103));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel15.add(jPanel17);

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel20.setPreferredSize(new java.awt.Dimension(165, 178));
        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 5));

        jPanel21.setBackground(new java.awt.Color(247, 251, 255));
        jPanel21.setPreferredSize(new java.awt.Dimension(157, 170));

        jLabel14.setBackground(new java.awt.Color(228, 232, 235));
        jLabel14.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(57, 72, 103));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Monthly Income");

        jLabel16.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(155, 164, 181));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("35000");
        jLabel16.setToolTipText("");

        jSeparator1.setBackground(new java.awt.Color(57, 72, 103));
        jSeparator1.setForeground(new java.awt.Color(57, 72, 103));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel20.add(jPanel21);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(247, 251, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(247, 251, 255));
        jLabel11.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(57, 72, 103));
        jLabel11.setText("Booking Details");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 150, -1));

        jLabel17.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(155, 164, 181));
        jLabel17.setText("Date");
        jLabel17.setPreferredSize(new java.awt.Dimension(70, 18));
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 23));

        dateRdBtn.setFont(new java.awt.Font("Poppins", 1, 10)); // NOI18N
        dateRdBtn.setForeground(new java.awt.Color(155, 164, 181));
        dateRdBtn.setText("Date");
        dateRdBtn.setPreferredSize(new java.awt.Dimension(65, 21));
        dateRdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateRdBtnActionPerformed(evt);
            }
        });
        jPanel7.add(dateRdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        customerNicRdBtn.setFont(new java.awt.Font("Poppins", 1, 10)); // NOI18N
        customerNicRdBtn.setForeground(new java.awt.Color(155, 164, 181));
        customerNicRdBtn.setText("Customer nic");
        customerNicRdBtn.setPreferredSize(new java.awt.Dimension(65, 21));
        customerNicRdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNicRdBtnActionPerformed(evt);
            }
        });
        jPanel7.add(customerNicRdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 105, -1));

        bookingSearchBtn.setBackground(new java.awt.Color(57, 72, 103));
        bookingSearchBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bookingSearchBtn.setForeground(new java.awt.Color(155, 164, 181));
        bookingSearchBtn.setText("Search");
        bookingSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingSearchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingSearchBtnMouseExited(evt);
            }
        });
        jPanel7.add(bookingSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 84, 48));

        jLabel19.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(155, 164, 181));
        jLabel19.setText("Customer nic");
        jLabel19.setPreferredSize(new java.awt.Dimension(70, 18));
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 110, -1));

        customerNicTextField2.setBackground(new java.awt.Color(255, 255, 255));
        customerNicTextField2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        customerNicTextField2.setForeground(new java.awt.Color(57, 72, 103));
        customerNicTextField2.setToolTipText("");
        customerNicTextField2.setActionCommand("<Not Set>");
        customerNicTextField2.setBorder(null);
        customerNicTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerNicTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNicTextField2FocusLost(evt);
            }
        });
        customerNicTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerNicTextField2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerNicTextField2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerNicTextField2MouseExited(evt);
            }
        });
        customerNicTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNicTextField2ActionPerformed(evt);
            }
        });
        jPanel7.add(customerNicTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, 30));

        bookingTable.setForeground(new java.awt.Color(155, 164, 181));
        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Hall no", "Date", "Payment ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookingTable.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        bookingTable.setSelectionBackground(new java.awt.Color(57, 72, 103));
        bookingTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        bookingTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(bookingTable);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 600, 380));
        jScrollPane1.setVerticalScrollBar(new resourceallocationsoftware.ViewClasses.Table.ScrollBar());

        jPanel1.setBackground(new java.awt.Color(247, 251, 255));

        jLabel5.setBackground(new java.awt.Color(247, 251, 255));
        jLabel5.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 72, 103));
        jLabel5.setText("Customer Search");

        customerSearchBtn.setBackground(new java.awt.Color(57, 72, 103));
        customerSearchBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        customerSearchBtn.setForeground(new java.awt.Color(155, 164, 181));
        customerSearchBtn.setText("Search");
        customerSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerSearchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerSearchBtnMouseExited(evt);
            }
        });
        customerSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSearchBtnActionPerformed(evt);
            }
        });

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setPreferredSize(new java.awt.Dimension(161, 58));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel14.setBackground(new java.awt.Color(247, 251, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(176, 50));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(155, 164, 181));
        jLabel12.setText("Customer nic");
        jLabel12.setPreferredSize(new java.awt.Dimension(70, 18));

        customerNicTf.setBackground(new java.awt.Color(247, 251, 255));
        customerNicTf.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        customerNicTf.setForeground(new java.awt.Color(67, 67, 67));
        customerNicTf.setToolTipText("");
        customerNicTf.setActionCommand("<Not Set>");
        customerNicTf.setBorder(null);
        customerNicTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerNicTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNicTfFocusLost(evt);
            }
        });
        customerNicTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerNicTfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerNicTfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerNicTfMouseExited(evt);
            }
        });
        customerNicTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNicTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addComponent(customerNicTf, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(customerNicTf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.add(jPanel14);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(customerSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        closeBtn.setBackground(new java.awt.Color(57, 72, 103));
        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(228, 232, 235));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_20px_2.png"))); // NOI18N
        closeBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });

        goBackBtn.setBackground(new java.awt.Color(57, 72, 103));
        goBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        goBackBtn.setForeground(new java.awt.Color(228, 232, 235));
        goBackBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_go_back_20px.png"))); // NOI18N
        goBackBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        goBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackBtnMouseExited(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(57, 72, 103));
        minimizeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeBtn.setForeground(new java.awt.Color(228, 232, 235));
        minimizeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_macos_minimize_20px_1.png"))); // NOI18N
        minimizeBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMovingLayout.createSequentialGroup()
                        .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGroup(panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(panelMoving, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        Icon icon = new ImageIcon("src/icon/icons8_cancel_20px_6.png");
        closeBtn.setIcon(icon);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        Icon icon = new ImageIcon("src/icon/icons8_cancel_20px_2.png");
        closeBtn.setIcon(icon);
    }//GEN-LAST:event_closeBtnMouseExited

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void goBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseClicked
        this.dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_goBackBtnMouseClicked

    private void goBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseEntered
        Icon icon = new ImageIcon("src/icon/icons8_go_back_20px_2.png");
        goBackBtn.setIcon(icon);
    }//GEN-LAST:event_goBackBtnMouseEntered

    private void goBackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseExited
        Icon icon = new ImageIcon("src/icon/icons8_go_back_20px.png");
        goBackBtn.setIcon(icon);
    }//GEN-LAST:event_goBackBtnMouseExited

    private void hallNoTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hallNoTfFocusGained
        jPanel8.setBackground(new Color(57, 72, 103));
        jLabel6.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_hallNoTfFocusGained

    private void hallNoTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hallNoTfFocusLost
        jPanel8.setBackground(new Color(204,204,204));
        jLabel6.setForeground(new Color(155,164,181));
        
    }//GEN-LAST:event_hallNoTfFocusLost

    private void hallNoTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hallNoTfMouseClicked

    }//GEN-LAST:event_hallNoTfMouseClicked

    private void hallNoTfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hallNoTfMouseEntered
        jPanel8.setBackground(new Color(57,72,103));
        jLabel6.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_hallNoTfMouseEntered

    private void hallNoTfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hallNoTfMouseExited
        jPanel8.setBackground(new Color(204,204,204));
        jLabel6.setForeground(new Color(155,164,181));
        

    }//GEN-LAST:event_hallNoTfMouseExited

    private void hallNoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallNoTfActionPerformed

    }//GEN-LAST:event_hallNoTfActionPerformed

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        jPanel8.setBackground(new Color(57,72,103));
        jLabel6.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel8.setBackground(new Color(204,204,204));
        jLabel6.setForeground(new Color(155,164,181));
        
    }//GEN-LAST:event_jPanel9MouseExited

    private void capacityTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capacityTfFocusGained
        jPanel10.setBackground(new Color(57, 72, 103));
        jLabel7.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_capacityTfFocusGained

    private void capacityTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capacityTfFocusLost
        jPanel10.setBackground(new Color(204,204,204));
        jLabel7.setForeground(new Color(155,164,181));
        
    }//GEN-LAST:event_capacityTfFocusLost

    private void capacityTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capacityTfMouseClicked

    }//GEN-LAST:event_capacityTfMouseClicked

    private void capacityTfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capacityTfMouseEntered
        jPanel10.setBackground(new Color(57,72,103));
        jLabel7.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_capacityTfMouseEntered

    private void capacityTfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capacityTfMouseExited
        jPanel10.setBackground(new Color(204,204,204));
        jLabel7.setForeground(new Color(155,164,181));
        

    }//GEN-LAST:event_capacityTfMouseExited

    private void capacityTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityTfActionPerformed

    }//GEN-LAST:event_capacityTfActionPerformed

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel10.setBackground(new Color(57,72,103));
        jLabel7.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        jPanel10.setBackground(new Color(204,204,204));
        jLabel7.setForeground(new Color(155,164,181));
        
    }//GEN-LAST:event_jPanel11MouseExited

    private void pricingTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pricingTfFocusGained
        jPanel12.setBackground(new Color(57, 72, 103));
        jLabel8.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_pricingTfFocusGained

    private void pricingTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pricingTfFocusLost
        jPanel12.setBackground(new Color(204,204,204));
        jLabel8.setForeground(new Color(155,164,181));
        
    }//GEN-LAST:event_pricingTfFocusLost

    private void pricingTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricingTfMouseClicked

    }//GEN-LAST:event_pricingTfMouseClicked

    private void pricingTfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricingTfMouseEntered
        jPanel12.setBackground(new Color(57,72,103));
        jLabel8.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_pricingTfMouseEntered

    private void pricingTfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pricingTfMouseExited
        jPanel12.setBackground(new Color(204,204,204));
        jLabel8.setForeground(new Color(155,164,181));
        

    }//GEN-LAST:event_pricingTfMouseExited

    private void pricingTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricingTfActionPerformed

    }//GEN-LAST:event_pricingTfActionPerformed

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        jPanel12.setBackground(new Color(57,72,103));
        jLabel8.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        jPanel12.setBackground(new Color(204,204,204));
        jLabel8.setForeground(new Color(155,164,181));
        
    }//GEN-LAST:event_jPanel13MouseExited

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        addBtn.setBackground(new Color(33, 42, 62));
        addBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        addBtn.setBackground(new Color(57,72,103));
        addBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_addBtnMouseExited

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        updateBtn.setBackground(new Color(33, 42, 62));
        updateBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        updateBtn.setBackground(new Color(57,72,103));
        updateBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_updateBtnMouseExited

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setBackground(new Color(33, 42, 62));
        deleteBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        deleteBtn.setBackground(new Color(57,72,103));
        deleteBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_deleteBtnMouseExited

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(Frame.ICONIFIED);
        
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        Icon icon = new ImageIcon("src/icon/icons8_macos_minimize_20px.png");
        minimizeBtn.setIcon(icon);
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        Icon icon = new ImageIcon("src/icon/icons8_macos_minimize_20px_1.png");
        minimizeBtn.setIcon(icon);
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void customerSearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerSearchBtnMouseEntered
        customerSearchBtn.setBackground(new Color(33, 42, 62));
        customerSearchBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_customerSearchBtnMouseEntered

    private void customerSearchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerSearchBtnMouseExited
        customerSearchBtn.setBackground(new Color(57,72,103));
        customerSearchBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_customerSearchBtnMouseExited

    private void customerNicTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNicTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTfFocusGained

    private void customerNicTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNicTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTfFocusLost

    private void customerNicTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNicTfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTfMouseClicked

    private void customerNicTfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNicTfMouseEntered
        jPanel16.setBackground(new Color(57,72,103));
        jLabel12.setForeground(new Color(57,72,103));
    }//GEN-LAST:event_customerNicTfMouseEntered

    private void customerNicTfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNicTfMouseExited
        jPanel16.setBackground(new Color(204,204,204));
        jLabel12.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_customerNicTfMouseExited

    private void customerNicTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNicTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTfActionPerformed

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        jPanel16.setBackground(new Color(57,72,103));
        jLabel12.setForeground(new Color(57,72,103));
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        jPanel16.setBackground(new Color(204,204,204));
        jLabel12.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_jPanel14MouseExited

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox1ActionPerformed

    private void customerNicTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNicTextField2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTextField2FocusGained

    private void customerNicTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNicTextField2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTextField2FocusLost

    private void customerNicTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNicTextField2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTextField2MouseClicked

    private void customerNicTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNicTextField2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTextField2MouseEntered

    private void customerNicTextField2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNicTextField2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTextField2MouseExited

    private void customerNicTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNicTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNicTextField2ActionPerformed

    private void dateRdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateRdBtnActionPerformed
        if(customerNicRdBtn.isEnabled()){
            customerNicRdBtn.setSelected(false);
        }
        customerNicRdBtn.setForeground(new Color(155,164,181));
        dateRdBtn.setForeground(new Color(57,72,103));
    }//GEN-LAST:event_dateRdBtnActionPerformed

    private void customerNicRdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNicRdBtnActionPerformed
        if(dateRdBtn.isEnabled()){
            dateRdBtn.setSelected(false);
        }
        dateRdBtn.setForeground(new Color(155,164,181));
        customerNicRdBtn.setForeground(new Color(57,72,103));
        
    }//GEN-LAST:event_customerNicRdBtnActionPerformed

    private void bookingSearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingSearchBtnMouseEntered
        bookingSearchBtn.setBackground(new Color(33, 42, 62));
        bookingSearchBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_bookingSearchBtnMouseEntered

    private void bookingSearchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingSearchBtnMouseExited
        bookingSearchBtn.setBackground(new Color(57,72,103));
        bookingSearchBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_bookingSearchBtnMouseExited

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int hallNo = Integer.parseInt(hallNoTf.getText());
        int capacity = Integer.parseInt(capacityTf.getText());
        double pricing = Double.parseDouble(pricingTf.getText());
        
        new HallManager().addHall(hallNo, capacity, pricing);
        
        fetchHallData();
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        int hallNo = Integer.parseInt(hallNoTf.getText());
        int capacity = Integer.parseInt(capacityTf.getText());
        double pricing = Double.parseDouble(pricingTf.getText());
        
        new HallManager().updateHall(hallNo, capacity, capacity);
        
        fetchHallData();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int hallNo = Integer.parseInt(hallNoTf.getText());
        
        new HallManager().deleteHall(hallNo);
        fetchHallData();
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void customerSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSearchBtnActionPerformed
        String nic = null;
        String name = null;
        String telephone = null;
        int customerId = Integer.parseInt(customerNicTf.getText());
        ResultSet rs;
        int userId = 0;
        
        try{
            DatabaseHandler dbHandler = new DatabaseHandler();
            PreparedStatement pstmt = dbHandler.getPreparedStatement("select userId from customer where customerId = ?");
            pstmt.setInt(1, customerId);
            rs = pstmt.executeQuery();
            if(rs.next()){
                userId = rs.getInt("userId");
            }
            pstmt = dbHandler.getPreparedStatement("select userNic,name from user where userId = ?");
            pstmt.setInt(1, userId);
            rs = pstmt.executeQuery();
            if(rs.next()){
                nic = rs.getString("userNic");
                name = rs.getString("name");
            }
            System.out.println(userId);
            pstmt = dbHandler.getPreparedStatement("select telephoneNumber,customerId from customer where userId = ?");
            pstmt.setInt(1, userId);
            rs = pstmt.executeQuery();
            if(rs.next()){
                telephone = rs.getString("telephoneNumber");
                customerId = rs.getInt("customerId");
            }
            System.out.println(nic+"--"+name+"--"+telephone+"--"+customerId);
            dbHandler.closeConnection();
        }catch(Exception e){
            e.printStackTrace();
        }
        
        new CustomerDetailsUI().showCustomerDetailsUI(name, nic, telephone);
        customerNicTf.setText("");
    }//GEN-LAST:event_customerSearchBtnActionPerformed

    private void hallDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hallDataMouseClicked
        int i = hallData.getSelectedRow();

        String hallID = hallData.getValueAt(i, 0).toString();
        String capacity = hallData.getValueAt(i, 1).toString();
        String pricing = hallData.getValueAt(i, 2).toString();

        hallNoTf.setText(hallID);
        capacityTf.setText(capacity);
        pricingTf.setText(pricing);
    }//GEN-LAST:event_hallDataMouseClicked

    private void hallDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hallDataFocusLost

    }//GEN-LAST:event_hallDataFocusLost
    
    /**
     * @param args the command line arguments
     */
    public void getAdminUI(Admin admin) {
        
        this.admin = admin;
        nicLabel.setText(admin.getNic());
        this.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminUI().setVisible(true);
//            }
//        });
    }

    
    private void fetchHallData(){
        DatabaseHandler dbHandler = new DatabaseHandler();
        DefaultTableModel dm = (DefaultTableModel) hallData.getModel();
        try {
        
            String query = "SELECT * FROM hall";
            PreparedStatement pst = dbHandler.getPreparedStatement(query);
            ResultSet rs = pst.executeQuery();
            dm.setRowCount(0);
        
        while (rs.next()) {
            
            Vector v = new Vector();
            v.add(rs.getInt("hallNumber"));
            v.add(rs.getInt("capacity"));
            v.add(rs.getInt("pricing"));
            
            dm.addRow(v);
        }
        
            
        } 
        catch (SQLException e) {
            e.printStackTrace();
        }
       
        dbHandler.closeConnection();
        
        
    }
    
    private void fetchBookingData(){
        
        int bookingId;
        int customerId;
        int hallNo;
        Date date;
        int paymentId;
        DefaultTableModel dm = (DefaultTableModel) bookingTable.getModel();
        try{
            DatabaseHandler dbHandler = new DatabaseHandler();
            PreparedStatement pstmt = dbHandler.getPreparedStatement("select * from booking");
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
                bookingId = rs.getInt("bookingId");
                customerId = rs.getInt("customerId");
                hallNo = rs.getInt("hallNumber");
                date = rs.getDate("date");
                paymentId = rs.getInt("paymentId");
                dm.addRow(new Object[]{bookingId,customerId,hallNo,date,paymentId});
            }
            dbHandler.closeConnection();
            System.out.println("Booking data added");
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private int x;
    private int y;
    
    public void initMoving(JFrame frame){
        panelMoving.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me){
                x = me.getX();
                y = me.getY();
            }
        });
        
        panelMoving.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me){
                frame.setLocation(me.getXOnScreen()-x, me.getYOnScreen()-y);
            }
        });
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton bookingSearchBtn;
    private resourceallocationsoftware.ViewClasses.Table.Table bookingTable;
    private javax.swing.JTextField capacityTf;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JRadioButton customerNicRdBtn;
    private javax.swing.JTextField customerNicTextField2;
    private javax.swing.JTextField customerNicTf;
    private javax.swing.JButton customerSearchBtn;
    private javax.swing.JRadioButton dateRdBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel goBackBtn;
    private resourceallocationsoftware.ViewClasses.Table.Table hallData;
    private javax.swing.JTextField hallNoTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JPanel panelMoving;
    private javax.swing.JTextField pricingTf;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
