/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourceallocationsoftware.ViewClasses;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
/**
 *
 * @author shanu
 */
public class CustomerMenuUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMenuUI
     */
    public CustomerMenuUI() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        initMoving(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new RoundPanel(50, 50, 50, 50);
        jPanel3 = new RoundPanel(50, 50, 0, 0);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new RoundPanel(30, 30, 30, 30);
        jPanel4 = new RoundPanel(30, 30, 30, 30);
        jLabel1 = new RoundLabel(30, 30, 30, 30);
        jPanel8 = new RoundPanel(30, 30, 30, 30);
        jPanel9 = new RoundPanel(20, 20, 20, 20);
        jLabel6 = new javax.swing.JLabel();
        loginIdTextField3 = new javax.swing.JTextField();
        jPanel10 = new RoundPanel(30, 30, 30, 30);
        jPanel11 = new RoundPanel(20, 20, 20, 20);
        jLabel7 = new javax.swing.JLabel();
        loginIdTextField4 = new javax.swing.JTextField();
        jPanel12 = new RoundPanel(30, 30, 30, 30);
        jPanel13 = new RoundPanel(20, 20, 20, 20);
        jLabel8 = new javax.swing.JLabel();
        loginIdTextField5 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel1 = new RoundPanel(20, 20, 20, 20);
        jPanel14 = new RoundPanel(10, 10, 10, 10);
        jLabel18 = new javax.swing.JLabel();
        combobox2 = new resourceallocationsoftware.ViewClasses.Combobox();
        combobox3 = new resourceallocationsoftware.ViewClasses.Combobox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        combobox4 = new resourceallocationsoftware.ViewClasses.Combobox();
        jLabel21 = new javax.swing.JLabel();
        loginIdTextField6 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new RoundPanel(30, 30, 30, 30);
        spHallTable = new javax.swing.JScrollPane();
        hallTable = new resourceallocationsoftware.ViewClasses.Table();
        jLabel9 = new RoundLabel(30, 30, 30, 30);
        jPanel6 = new RoundPanel(30, 30, 30, 30);
        jLabel10 = new RoundLabel(30, 30, 30, 30);
        jPanel15 = new RoundPanel(20, 20, 20, 20);
        jPanel17 = new RoundPanel(10, 10, 10, 10);
        jPanel7 = new RoundPanel(30, 30, 30, 30);
        spCustomerTable = new javax.swing.JScrollPane();
        bookingTable = new resourceallocationsoftware.ViewClasses.Table();
        jLabel11 = new RoundLabel(30, 30, 30, 30);
        combobox1 = new resourceallocationsoftware.ViewClasses.Combobox();
        jLabel17 = new javax.swing.JLabel();
        bookingSearchBtn = new javax.swing.JButton();
        closeBtn = new RoundLabel(0, 0, 50, 0);
        goBackBtn = new RoundLabel(0, 0, 50, 0);
        minimizeBtn = new RoundLabel(0, 0, 50, 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        panelMoving.setBackground(new java.awt.Color(57, 72, 103));
        panelMoving.setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel3.setBackground(new java.awt.Color(57, 72, 103));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 800));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_book_75px.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 251, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Booking");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 251, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("menu");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(228, 232, 235));
        jPanel2.setPreferredSize(new java.awt.Dimension(1075, 750));

        jPanel4.setBackground(new java.awt.Color(247, 251, 255));

        jLabel1.setBackground(new java.awt.Color(247, 251, 255));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 72, 103));
        jLabel1.setText("Booking Manager");

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel9.setBackground(new java.awt.Color(247, 251, 255));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(217, 50));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(155, 164, 181));
        jLabel6.setText("Hall no");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 18));

        loginIdTextField3.setEditable(false);
        loginIdTextField3.setBackground(new java.awt.Color(247, 251, 255));
        loginIdTextField3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginIdTextField3.setForeground(new java.awt.Color(67, 67, 67));
        loginIdTextField3.setToolTipText("");
        loginIdTextField3.setActionCommand("<Not Set>");
        loginIdTextField3.setBorder(null);
        loginIdTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginIdTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginIdTextField3FocusLost(evt);
            }
        });
        loginIdTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginIdTextField3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginIdTextField3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginIdTextField3MouseExited(evt);
            }
        });
        loginIdTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIdTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginIdTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(loginIdTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel11.setBackground(new java.awt.Color(247, 251, 255));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(217, 50));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(155, 164, 181));
        jLabel7.setText("Capacity");
        jLabel7.setPreferredSize(new java.awt.Dimension(70, 18));

        loginIdTextField4.setEditable(false);
        loginIdTextField4.setBackground(new java.awt.Color(247, 251, 255));
        loginIdTextField4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginIdTextField4.setForeground(new java.awt.Color(67, 67, 67));
        loginIdTextField4.setToolTipText("");
        loginIdTextField4.setActionCommand("<Not Set>");
        loginIdTextField4.setBorder(null);
        loginIdTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginIdTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginIdTextField4FocusLost(evt);
            }
        });
        loginIdTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginIdTextField4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginIdTextField4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginIdTextField4MouseExited(evt);
            }
        });
        loginIdTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIdTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginIdTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(loginIdTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel13.setBackground(new java.awt.Color(247, 251, 255));
        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(217, 50));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(155, 164, 181));
        jLabel8.setText("Pricing");
        jLabel8.setPreferredSize(new java.awt.Dimension(70, 18));

        loginIdTextField5.setEditable(false);
        loginIdTextField5.setBackground(new java.awt.Color(247, 251, 255));
        loginIdTextField5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginIdTextField5.setForeground(new java.awt.Color(67, 67, 67));
        loginIdTextField5.setToolTipText("");
        loginIdTextField5.setActionCommand("<Not Set>");
        loginIdTextField5.setBorder(null);
        loginIdTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginIdTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginIdTextField5FocusLost(evt);
            }
        });
        loginIdTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginIdTextField5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginIdTextField5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginIdTextField5MouseExited(evt);
            }
        });
        loginIdTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIdTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginIdTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(loginIdTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel13);

        addBtn.setBackground(new java.awt.Color(57, 72, 103));
        addBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(155, 164, 181));
        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(57, 72, 103));
        deleteBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(155, 164, 181));
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(211, 186));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel14.setBackground(new java.awt.Color(247, 251, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(203, 178));

        jLabel18.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(155, 164, 181));
        jLabel18.setText("Day");
        jLabel18.setPreferredSize(new java.awt.Dimension(70, 18));

        combobox2.setBorder(null);
        combobox2.setForeground(new java.awt.Color(57, 72, 103));
        combobox2.setMaximumRowCount(32);
        combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combobox2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        combobox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox2ActionPerformed(evt);
            }
        });

        combobox3.setBorder(null);
        combobox3.setForeground(new java.awt.Color(57, 72, 103));
        combobox3.setMaximumRowCount(32);
        combobox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " ", " " }));
        combobox3.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        combobox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(155, 164, 181));
        jLabel19.setText("Month");
        jLabel19.setPreferredSize(new java.awt.Dimension(70, 18));

        jLabel20.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(155, 164, 181));
        jLabel20.setText("Year");
        jLabel20.setPreferredSize(new java.awt.Dimension(70, 18));

        combobox4.setBorder(null);
        combobox4.setForeground(new java.awt.Color(57, 72, 103));
        combobox4.setMaximumRowCount(32);
        combobox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", " " }));
        combobox4.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        combobox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox4ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(155, 164, 181));
        jLabel21.setText("Date");
        jLabel21.setPreferredSize(new java.awt.Dimension(70, 18));

        loginIdTextField6.setEditable(false);
        loginIdTextField6.setBackground(new java.awt.Color(255, 255, 255));
        loginIdTextField6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        loginIdTextField6.setForeground(new java.awt.Color(67, 67, 67));
        loginIdTextField6.setToolTipText("");
        loginIdTextField6.setActionCommand("<Not Set>");
        loginIdTextField6.setBorder(null);
        loginIdTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginIdTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginIdTextField6FocusLost(evt);
            }
        });
        loginIdTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginIdTextField6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginIdTextField6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginIdTextField6MouseExited(evt);
            }
        });
        loginIdTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIdTextField6ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(57, 72, 103));
        jSeparator2.setForeground(new java.awt.Color(57, 72, 103));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combobox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combobox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(loginIdTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(loginIdTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel14);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        jPanel5.setBackground(new java.awt.Color(247, 251, 255));

        hallTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall no", "Capacity", "Pricing"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hallTable.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        hallTable.setSelectionBackground(new java.awt.Color(57, 72, 103));
        hallTable.setSelectionForeground(new java.awt.Color(247, 251, 255));
        hallTable.getTableHeader().setReorderingAllowed(false);
        spHallTable.setViewportView(hallTable);

        jLabel9.setBackground(new java.awt.Color(247, 251, 255));
        jLabel9.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(57, 72, 103));
        jLabel9.setText("Hall Data");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spHallTable, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spHallTable, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spHallTable.setVerticalScrollBar(new ScrollBar());
        spHallTable.getVerticalScrollBar().setBackground(new Color(247,251,255));
        spHallTable.getViewport().setBackground(new Color(247,251,255));
        JPanel hp = new JPanel();
        hp.setBackground(new Color(247,251,255));
        spCustomerTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, hp);

        jPanel6.setBackground(new java.awt.Color(247, 251, 255));

        jLabel10.setBackground(new java.awt.Color(247, 251, 255));
        jLabel10.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(57, 72, 103));
        jLabel10.setText("Customer Data");

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setPreferredSize(new java.awt.Dimension(360, 212));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 4));

        jPanel17.setBackground(new java.awt.Color(247, 251, 255));
        jPanel17.setPreferredSize(new java.awt.Dimension(352, 204));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel17);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(247, 251, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookingTable.setForeground(new java.awt.Color(137, 145, 160));
        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Hall no", "Date", "Payment ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookingTable.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        bookingTable.setSelectionBackground(new java.awt.Color(57, 72, 103));
        bookingTable.setSelectionForeground(new java.awt.Color(247, 251, 255));
        bookingTable.getTableHeader().setReorderingAllowed(false);
        spCustomerTable.setViewportView(bookingTable);

        jPanel7.add(spCustomerTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 76, 605, 368));
        spCustomerTable.setVerticalScrollBar(new ScrollBar());
        spCustomerTable.getVerticalScrollBar().setBackground(new Color(247,251,255));
        spCustomerTable.getViewport().setBackground(new Color(247,251,255));
        JPanel p = new JPanel();
        p.setBackground(new Color(247,251,255));
        spCustomerTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

        jLabel11.setBackground(new java.awt.Color(247, 251, 255));
        jLabel11.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(57, 72, 103));
        jLabel11.setText("Booking Details");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 150, -1));

        combobox1.setBorder(null);
        combobox1.setForeground(new java.awt.Color(57, 72, 103));
        combobox1.setMaximumRowCount(32);
        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combobox1.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });
        jPanel7.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 38, -1));

        jLabel17.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(155, 164, 181));
        jLabel17.setText("Date");
        jLabel17.setPreferredSize(new java.awt.Dimension(70, 18));
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 51, 23));

        bookingSearchBtn.setBackground(new java.awt.Color(57, 72, 103));
        bookingSearchBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bookingSearchBtn.setForeground(new java.awt.Color(155, 164, 181));
        bookingSearchBtn.setText("Search");
        bookingSearchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingSearchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingSearchBtnMouseExited(evt);
            }
        });
        jPanel7.add(bookingSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 84, 48));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        closeBtn.setBackground(new java.awt.Color(57, 72, 103));
        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(228, 232, 235));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_20px_2.png"))); // NOI18N
        closeBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });

        goBackBtn.setBackground(new java.awt.Color(57, 72, 103));
        goBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        goBackBtn.setForeground(new java.awt.Color(228, 232, 235));
        goBackBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_go_back_20px.png"))); // NOI18N
        goBackBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        goBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackBtnMouseExited(evt);
            }
        });

        minimizeBtn.setBackground(new java.awt.Color(57, 72, 103));
        minimizeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minimizeBtn.setForeground(new java.awt.Color(228, 232, 235));
        minimizeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_macos_minimize_20px_1.png"))); // NOI18N
        minimizeBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMovingLayout.createSequentialGroup()
                        .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGroup(panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimizeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(panelMoving, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginIdTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField3FocusGained
        jPanel8.setBackground(new Color(57, 72, 103));
        jLabel6.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_loginIdTextField3FocusGained

    private void loginIdTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField3FocusLost
        jPanel8.setBackground(new Color(204,204,204));
        jLabel6.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_loginIdTextField3FocusLost

    private void loginIdTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField3MouseClicked

    }//GEN-LAST:event_loginIdTextField3MouseClicked

    private void loginIdTextField3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField3MouseEntered
        jPanel8.setBackground(new Color(57,72,103));
        jLabel6.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_loginIdTextField3MouseEntered

    private void loginIdTextField3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField3MouseExited
        jPanel8.setBackground(new Color(204,204,204));
        jLabel6.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_loginIdTextField3MouseExited

    private void loginIdTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIdTextField3ActionPerformed

    }//GEN-LAST:event_loginIdTextField3ActionPerformed

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        jPanel8.setBackground(new Color(57,72,103));
        jLabel6.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel8.setBackground(new Color(204,204,204));
        jLabel6.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_jPanel9MouseExited

    private void loginIdTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField4FocusGained
        jPanel10.setBackground(new Color(57, 72, 103));
        jLabel7.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_loginIdTextField4FocusGained

    private void loginIdTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField4FocusLost
        jPanel10.setBackground(new Color(204,204,204));
        jLabel7.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_loginIdTextField4FocusLost

    private void loginIdTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField4MouseClicked

    }//GEN-LAST:event_loginIdTextField4MouseClicked

    private void loginIdTextField4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField4MouseEntered
        jPanel10.setBackground(new Color(57,72,103));
        jLabel7.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_loginIdTextField4MouseEntered

    private void loginIdTextField4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField4MouseExited
        jPanel10.setBackground(new Color(204,204,204));
        jLabel7.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_loginIdTextField4MouseExited

    private void loginIdTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIdTextField4ActionPerformed

    }//GEN-LAST:event_loginIdTextField4ActionPerformed

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel10.setBackground(new Color(57,72,103));
        jLabel7.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        jPanel10.setBackground(new Color(204,204,204));
        jLabel7.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_jPanel11MouseExited

    private void loginIdTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField5FocusGained
        jPanel12.setBackground(new Color(57, 72, 103));
        jLabel8.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_loginIdTextField5FocusGained

    private void loginIdTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField5FocusLost
        jPanel12.setBackground(new Color(204,204,204));
        jLabel8.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_loginIdTextField5FocusLost

    private void loginIdTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField5MouseClicked

    }//GEN-LAST:event_loginIdTextField5MouseClicked

    private void loginIdTextField5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField5MouseEntered
        jPanel12.setBackground(new Color(57,72,103));
        jLabel8.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_loginIdTextField5MouseEntered

    private void loginIdTextField5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField5MouseExited
        jPanel12.setBackground(new Color(204,204,204));
        jLabel8.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_loginIdTextField5MouseExited

    private void loginIdTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIdTextField5ActionPerformed

    }//GEN-LAST:event_loginIdTextField5ActionPerformed

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        jPanel12.setBackground(new Color(57,72,103));
        jLabel8.setForeground(new Color(57,72,103));

    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        jPanel12.setBackground(new Color(204,204,204));
        jLabel8.setForeground(new Color(155,164,181));

    }//GEN-LAST:event_jPanel13MouseExited

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        addBtn.setBackground(new Color(33, 42, 62));
        addBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        addBtn.setBackground(new Color(57,72,103));
        addBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_addBtnMouseExited

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setBackground(new Color(33, 42, 62));
        deleteBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        deleteBtn.setBackground(new Color(57,72,103));
        deleteBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_deleteBtnMouseExited

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox1ActionPerformed

    private void bookingSearchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingSearchBtnMouseEntered
        bookingSearchBtn.setBackground(new Color(33, 42, 62));
        bookingSearchBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_bookingSearchBtnMouseEntered

    private void bookingSearchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingSearchBtnMouseExited
        bookingSearchBtn.setBackground(new Color(57,72,103));
        bookingSearchBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_bookingSearchBtnMouseExited

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        Icon icon = new ImageIcon("src/icon/icons8_cancel_20px_6.png");
        closeBtn.setIcon(icon);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        Icon icon = new ImageIcon("src/icon/icons8_cancel_20px_2.png");
        closeBtn.setIcon(icon);
    }//GEN-LAST:event_closeBtnMouseExited

    private void goBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseClicked
        this.dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_goBackBtnMouseClicked

    private void goBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseEntered
        Icon icon = new ImageIcon("src/icon/icons8_go_back_20px_2.png");
        goBackBtn.setIcon(icon);
    }//GEN-LAST:event_goBackBtnMouseEntered

    private void goBackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseExited
        Icon icon = new ImageIcon("src/icon/icons8_go_back_20px.png");
        goBackBtn.setIcon(icon);
    }//GEN-LAST:event_goBackBtnMouseExited

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        this.setState(Frame.ICONIFIED);

    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void minimizeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseEntered
        Icon icon = new ImageIcon("src/icon/icons8_macos_minimize_20px.png");
        minimizeBtn.setIcon(icon);
    }//GEN-LAST:event_minimizeBtnMouseEntered

    private void minimizeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseExited
        Icon icon = new ImageIcon("src/icon/icons8_macos_minimize_20px_1.png");
        minimizeBtn.setIcon(icon);
    }//GEN-LAST:event_minimizeBtnMouseExited

    private void combobox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox2ActionPerformed

    private void combobox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox3ActionPerformed

    private void combobox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox4ActionPerformed

    private void loginIdTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIdTextField6FocusGained

    private void loginIdTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginIdTextField6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIdTextField6FocusLost

    private void loginIdTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIdTextField6MouseClicked

    private void loginIdTextField6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIdTextField6MouseEntered

    private void loginIdTextField6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginIdTextField6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIdTextField6MouseExited

    private void loginIdTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIdTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIdTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMenuUI().setVisible(true);
            }
        });
    }
    
    
    private int x;
    private int y;
    
    public void initMoving(JFrame frame){
        panelMoving.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me){
                x = me.getX();
                y = me.getY();
            }
        });
        
        panelMoving.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me){
                frame.setLocation(me.getXOnScreen()-x, me.getYOnScreen()-y);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton bookingSearchBtn;
    private resourceallocationsoftware.ViewClasses.Table bookingTable;
    private javax.swing.JLabel closeBtn;
    private resourceallocationsoftware.ViewClasses.Combobox combobox1;
    private resourceallocationsoftware.ViewClasses.Combobox combobox2;
    private resourceallocationsoftware.ViewClasses.Combobox combobox3;
    private resourceallocationsoftware.ViewClasses.Combobox combobox4;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel goBackBtn;
    private resourceallocationsoftware.ViewClasses.Table hallTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField loginIdTextField3;
    private javax.swing.JTextField loginIdTextField4;
    private javax.swing.JTextField loginIdTextField5;
    private javax.swing.JTextField loginIdTextField6;
    private javax.swing.JLabel minimizeBtn;
    private javax.swing.JPanel panelMoving;
    private javax.swing.JScrollPane spCustomerTable;
    private javax.swing.JScrollPane spHallTable;
    // End of variables declaration//GEN-END:variables
}
