/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resourceallocationsoftware.ViewClasses;

import java.awt.Color;

/**
 *
 * @author shanu
 */
public class RecuringUI extends javax.swing.JFrame {

    /**
     * Creates new form PeriodicUI
     */
    public RecuringUI() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startingDateChooser = new com.raven.datechooser.DateChooser();
        endDateChooser = new com.raven.datechooser.DateChooser();
        jPanel1 = new RoundPanel(30, 30, 30, 30);
        jPanel2 = new RoundPanel(20, 20, 20, 20);
        startingDateTf = new textfield.TextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        endDateTf = new textfield.TextField();

        startingDateChooser.setBackground(new java.awt.Color(247, 251, 255));
        startingDateChooser.setForeground(new java.awt.Color(57, 72, 103));
        startingDateChooser.setDateFormat("dd-MMMM-yyyy");
        startingDateChooser.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        startingDateChooser.setTextRefernce(startingDateTf);

        endDateChooser.setBackground(new java.awt.Color(247, 251, 255));
        endDateChooser.setForeground(new java.awt.Color(57, 72, 103));
        endDateChooser.setDateFormat("dd-MMMM-yyyy");
        endDateChooser.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        endDateChooser.setTextRefernce(endDateTf);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(57, 72, 103));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 15));

        jPanel2.setBackground(new java.awt.Color(247, 251, 255));
        jPanel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(322, 239));

        startingDateTf.setForeground(new java.awt.Color(155, 164, 181));
        startingDateTf.setCaretColor(new java.awt.Color(155, 164, 181));
        startingDateTf.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        startingDateTf.setLabelText("Starting Date");
        startingDateTf.setLineColor(new java.awt.Color(57, 72, 103));
        startingDateTf.setSelectionColor(new java.awt.Color(57, 72, 103));

        okBtn.setBackground(new java.awt.Color(57, 72, 103));
        okBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        okBtn.setForeground(new java.awt.Color(155, 164, 181));
        okBtn.setText("Ok");
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okBtnMouseExited(evt);
            }
        });
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(57, 72, 103));
        cancelBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(155, 164, 181));
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
        });
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(57, 72, 103));
        jLabel12.setText("Select Date");
        jLabel12.setPreferredSize(new java.awt.Dimension(70, 18));

        endDateTf.setForeground(new java.awt.Color(155, 164, 181));
        endDateTf.setCaretColor(new java.awt.Color(155, 164, 181));
        endDateTf.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        endDateTf.setLabelText("End Date");
        endDateTf.setLineColor(new java.awt.Color(57, 72, 103));
        endDateTf.setSelectionColor(new java.awt.Color(57, 72, 103));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startingDateTf, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(endDateTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startingDateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(endDateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseEntered
        okBtn.setBackground(new Color(33, 42, 62));
        okBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_okBtnMouseEntered

    private void okBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseExited
        okBtn.setBackground(new Color(57,72,103));
        okBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_okBtnMouseExited

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        cancelBtn.setBackground(new Color(33, 42, 62));
        cancelBtn.setForeground(new Color(247,251,255));
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        cancelBtn.setBackground(new Color(57,72,103));
        cancelBtn.setForeground(new Color(155,164,181));
    }//GEN-LAST:event_cancelBtnMouseExited

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();

    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showRecuringUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuringUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuringUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private com.raven.datechooser.DateChooser endDateChooser;
    private textfield.TextField endDateTf;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton okBtn;
    private com.raven.datechooser.DateChooser startingDateChooser;
    private textfield.TextField startingDateTf;
    // End of variables declaration//GEN-END:variables
}
